name: John Git Action
run-name: John Git Action
on: [push]

env:
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 SSH_KEY_PEM: ${{ secrets.SSH_KEY_PEM }}


jobs:
  Simple_Test_For_Now:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code from repo
       uses: actions/checkout@v4

     - name: Setup Terraform to implement Cloud Infra
       uses: hashicorp/setup-terraform@v2
       with: 
         terraform_version: 1.3.0

     - name: Terraform init
       run: terraform init
  
     - name: Terraform Plan
       run: terraform plan
  
     - name: Terraform Apply
       run: terraform apply --auto-approve
         
     - name: Create .ssh directory
       run: mkdir -p ~/.ssh

     - name: Set up PEM key
       run: |
            echo "${{ secrets.SSH_KEY_PEM }}" > ~/.ssh/jonag.pem
            chmod 600 ~/.ssh/jonag.pem
            ssh-keyscan -H "ec2-35-177-155-56.eu-west-2.compute.amazonaws.com" >> ~/.ssh/known_hosts
  
     - name: SSH into EC2 with PEM
       run:  |
             ssh -i ~/.ssh/jonag.pem ec2-user@ec2-35-177-155-56.eu-west-2.compute.amazonaws.com "echo 'Connected to EC2 instance'"

    

    #  - name: Terraform Destroy
    #    run: terraform destroy --auto-approve
       
