name: Techbleat Git Action
run-name: Techbleat Git Action
on: [push]
jobs:
  Simple_Test_For_Now:
   runs-on: ubuntu-latest
   steps:
     - name: checkout code from repo
       uses: actions/checkout@v4

     - name: Setup Terraform to implement Cloud Infr
       uses: hashicorp/setup-terraform@v2
       with: 
         terraform_version: 1.3.0

     - name: Terraform init
       run: terraform init
